apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  server.insecure: "false"
  users.anonymous.enabled: "false"
  admin.enabled: "true"
  url: "https://argocd.campbaloise.ch"
  # https://docs.crossplane.io/knowledge-base/integrations/argo-cd-crossplane/#set-resource-tracking-method
  application.resourceTrackingMethod: "annotation"
  # https://docs.crossplane.io/knowledge-base/integrations/argo-cd-crossplane/#set-resource-exclusion
  resource.exclusions: |
    - apiGroups:
      - "*"
      kinds:
      - ProviderConfigUsage
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $github-argocd-oauth-client:client-id
          clientSecret: $github-argocd-oauth-client:client-secret
          orgs:
          - name: baloise-incubator