apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azure-family
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  package: xpkg.upbound.io/upbound/provider-family-azure:v0.42.1