apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: UserAssignedManagedIdentity
  clientID: 7bd1b65c-94e2-48b2-b5d9-783ac4578462
  subscriptionID: 3e4d97c2-8bd1-4b12-99ed-303d1b77c4cc
  tenantID: 922474ff-3ade-465e-9be4-04730b10a029