apiVersion: dbforpostgresql.azure.upbound.io/v1beta2
kind: Server
metadata:
  name: example-server-3
spec:
  forProvider:
    administratorLogin: psqladmin
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: default
    location: Germany West Central
    autoGrowEnabled: false
    backupRetentionDays: 7
    geoRedundantBackupEnabled: false
    sslEnforcementEnabled: true
    resourceGroupNameRef:
      name: example-postgres-1
    skuName: B_Gen5_2
    storageMb: 32768
    version: '14'
