apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
kind: Server
metadata:
  name: example-server-3
spec:
  forProvider:
    administratorLogin: psqladmin
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    location: Germany West Central
    autoGrowEnabled: false
    backupRetentionDays: 7
    geoRedundantBackupEnabled: false
    resourceGroupNameRef:
      name: example-postgres-1
    skuName: GP_Standard_D2s_v3
    storageMb: 32768
    version: '14'
