apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: postgresqldatabases.databases.platform.baloise.app
spec:
  group: databases.platform.baloise.app
  names:
    kind: PostgreSQLDatabase
    plural: postgresqldatabases
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deletionPolicy:
                  type: string
                  default: Delete
                  enum:
                    - Delete
                    - Orphan
                location:
                  type: string
              required:
                - location
      served: true
      referenceable: true
  claimNames:
    kind: PostgreSQLDatabaseClaim
    plural: postgresqldatabaseclaims
---