apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azure-dbforpostgresql
spec:
  package: docker.io/niiku/provider-azure-amd64:build-e2b175f8-5
  controllerConfigRef:
    name: debug-config