apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
kind: FlexibleServerDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1beta1/FlexibleServer
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    charset: utf8
    collation: en_US.utf8
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example