apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  credentials:
    source: UserAssignedManagedIdentity
  clientID: 42d57721-c3c9-4328-8600-f3f6541b6d5b
  subscriptionID: 3e4d97c2-8bd1-4b12-99ed-303d1b77c4cc
  tenantID: 922474ff-3ade-465e-9be4-04730b10a029