apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: foo
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: resourcegroup-test
  managementPolicy: ObserveDelete
  providerConfigRef:
    name: kubernetes-provider