apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
kind: FlexibleServer
metadata:
  name: example
  labels:
    testing.upbound.io/example-name: example
spec:
  forProvider:
    administrator_login_password: 4-v3ry-53cr37-p455w0rd
    administratorLogin: 4dm1n157r470r
    authentication:
      - activeDirectoryAuthEnabled: true
        tenantId: ${data.azurerm_client_config.current.tenant_id}
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: GP_Standard_B1ms
    storageMb: 32768
    version: "16"