apiVersion: dbforpostgresql.azure.upbound.io/v1beta2
kind: FlexibleServer
metadata:
  name: example
  labels:
    testing.upbound.io/example-name: example
spec:
  forProvider:
    authentication:
      activeDirectoryAuthEnabled: true
      passwordAuthEnabled: false
      tenantId: "922474ff-3ade-465e-9be4-04730b10a029"
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: GP_Standard_D2ads_v5
    storageMb: 32768
    version: "16"