apiVersion: cache.azure.upbound.io/v1beta1
kind: RedisCache
metadata:
  name: my-b03786-redis
spec:
  forProvider:
    capacity: 0
    enableNonSslPort: false
    family: C
    location: West Europe
    minimumTlsVersion: "1.2"
    redisVersion: "6"
    redisConfiguration: {}
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: Basic
---
apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: myawesomerg
spec:
  forProvider:
    location: "West Europe"
---
apiVersion: cache.azure.upbound.io/v1beta1
kind: RedisCache
metadata:
  name: my-b03786-redis-2
spec:
  forProvider:
    capacity: 0
    enableNonSslPort: false
    family: C
    location: West Europe
    minimumTlsVersion: "1.2"
    redisVersion: "6"
    redisConfiguration: {}
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: Basic
---
apiVersion: cache.azure.upbound.io/v1beta1
kind: RedisCache
metadata:
  name: my-b03786-redis-3
spec:
  forProvider:
    capacity: 0
    enableNonSslPort: false
    family: C
    location: West Europe
    minimumTlsVersion: "1.2"
    redisVersion: "6"
    redisConfiguration: {}
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: Basic
---
apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
kind: FlexibleServer
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1beta2/flexibleserver
  labels:
    testing.upbound.io/example-name: example
  name: example-flexydexy-2
spec:
  deletionPolicy: Delete
  forProvider:
    authentication:
      activeDirectoryAuthEnabled: true
      passwordAuthEnabled: false
    location: Germany West Central
    resourceGroupNameRef:
      name: example-postgres-1
    skuName: GP_Standard_D2s_v3
    storageMb: 32768
    version: '14'
