---
apiVersion: crossplane.giantswarm.io/v1alpha1
kind: ApdbClaim
metadata:
  name: test-crossplane-azure-pgsql
  namespace: default
  labels:
    owner: giantswarm
spec:
  name: tcap-sql
  namespace: default
  compositionSelector:
    matchLabels:
      provider: azure
      example: postgres-vnet
  parameters:
    providerConfigRef: default
    location: West Europe
    vnetRanges:
      - 10.9.0.0/24
    subnets:
      public: 10.9.0.0/25
      private: 10.9.0.128/25
    sku: GP_Standard_D4s_v3
    db:
      version: "14"
      admin: giantswarm
      secret:
        name: azure-db-pass
        key: database-password
      firewall:
        startAddr: 10.0.0.0
        endAddr: 10.0.0.0
    remoteResourceGroup:
      name: MC_rg-lasting-peacock_aks-lasting-peacock_germanywestcentral
      vnetId: "/subscriptions/3e4d97c2-8bd1-4b12-99ed-303d1b77c4cc/resourceGroups/MC_rg-lasting-peacock_aks-lasting-peacock_germanywestcentral/providers/Microsoft.Network/virtualNetworks/aks-vnet-15142108"
      vnetName: aks-vnet-15142108
