apiVersion: cache.azure.upbound.io/v1beta2
kind: RedisCache
metadata:
  annotations:
    meta.upbound.io/example-id: cache/v1beta2/rediscache
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    capacity: 0
    enableNonSslPort: false
    family: C
    location: West Europe
    minimumTlsVersion: "1.2"
    redisVersion: "6"
    redisConfiguration: {}
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: Basic