apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

resources:
  - base/external-dns-namespace.yaml
  - base/cf-api-token-external-secret.yaml
  # Use master file, as 0.14.2 has not yet the fix for api-approved annotation
  - https://raw.githubusercontent.com/kubernetes-sigs/external-dns/master/docs/contributing/crd-source/crd-manifest.yaml
  - https://github.com/kubernetes-sigs/external-dns/kustomize?ref=v0.14.2

patches:
  - path: overlays/external-dns-deployment.yaml
  - path: overlays/external-dns-cluster-role.yaml
